-- Tabla para el SaaS JobHunter
CREATE TABLE IF NOT EXISTS ofertas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    empresa TEXT NOT NULL,
    titulo TEXT NOT NULL,
    fecha_aplicacion DATE NOT NULL,
    tipo TEXT NOT NULL,
    salario TEXT,
    observaciones TEXT,
    estado TEXT DEFAULT 'en_espera',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE ofertas ENABLE ROW LEVEL SECURITY;

-- Política: usuarios solo pueden ver/editar sus propias ofertas
CREATE POLICY "ofertas_usuario" ON ofertas FOR ALL 
USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Tabla de perfiles de usuario
CREATE TABLE IF NOT EXISTS perfiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Trigger para crear perfil automáticamente
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.perfiles (id, email)
    VALUES (NEW.id, NEW.email);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Crear trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
